apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
