---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample
data:
  URL: gotomeeting.com
  TIMING: 7.30AMIST
  COURSE: DEVOPS

---
apiVersion: v1
kind: Pod
metadata:
  name: sample2
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "10000"]
      envFrom:
        - configMapRef:
            name: sample
