---
apiVersion: v1
kind: Secret
metadata:
  name: sample
data:
  URL: "Z290b21lZXRpbmcuY29tCg=="

---
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "10000"]
      envFrom:
        - secretRef:
            name: sample
